import {
  LayoutDashboard,
  GitBranch,
  Users,
  Landmark,
  Calculator,
  Activity,
  BarChart3,
  Factory,
  ClipboardList,
  FolderOpen,
  Percent,
  Receipt,
  ReceiptText,
  Wallet,
  Banknote,
  FileText,
  UserCog,
  Bell,
  ScrollText,
  ListTodo,
  HandCoins,
  Coins,
  ShieldCheck,
  Send,
  FileSignature,
  Gavel,
  CalendarDays,
  type LucideIcon,
} from "lucide-react";

export type NavItem = {
  to: string;
  label: string;
  icon: LucideIcon;
};

// Primary navigation, shared by the sidebar across all screens.
export const NAV_ITEMS: NavItem[] = [
  { to: "/dashboard", label: "Dashboard", icon: LayoutDashboard },
  { to: "/leads", label: "Leads", icon: ClipboardList },
  { to: "/pipeline", label: "Pipeline", icon: GitBranch },
  { to: "/tasks", label: "Tasks", icon: ListTodo },
  { to: "/calendar", label: "Calendar", icon: CalendarDays },
  { to: "/clients", label: "Clients", icon: Users },
  { to: "/client-invitations", label: "Client Invitations", icon: Send },
  { to: "/documents", label: "Documents", icon: FolderOpen },
  { to: "/funders", label: "Funders", icon: Landmark },
  { to: "/invoices", label: "Invoices", icon: Receipt },
  { to: "/repayments", label: "Repayments", icon: HandCoins },
  { to: "/invoices/partner-approvals", label: "Partner Invoices", icon: ReceiptText },
  { to: "/invoices/contractor-approvals", label: "Contractor Invoices", icon: ReceiptText },
  { to: "/partner-earnings", label: "Partner Earnings", icon: Wallet },
  { to: "/payouts", label: "Payouts", icon: Coins },
  { to: "/statements", label: "Statements", icon: FileText },
  { to: "/calculator", label: "Calculator", icon: Calculator },
  { to: "/activity", label: "Activity", icon: Activity },
  { to: "/reports", label: "Reports", icon: BarChart3 },
  { to: "/data-quality", label: "Data Quality", icon: ShieldCheck },
  { to: "/team", label: "Team", icon: UserCog },
  { to: "/settings/notifications", label: "Notifications", icon: Bell },
  { to: "/settings/industries", label: "Industries", icon: Factory },
  { to: "/settings/funders", label: "Funder rates", icon: Percent },
  { to: "/settings/payees", label: "Payee banking", icon: Banknote },
  { to: "/settings/terms", label: "Terms", icon: ScrollText },
  { to: "/agreements", label: "Agreements", icon: FileSignature },
  { to: "/settings/legal-studio", label: "Document Studio", icon: Gavel },
];
