import { useMemo, useState, type FormEvent } from "react";
import { Check, Loader2, Plus, RotateCcw } from "lucide-react";
import { toast } from "sonner";
import { useCreateOwnerTask, useOwnerTasks, useSetOwnerTaskStatus } from "@/hooks/useOwnerTasks";

export default function TasksPage() {
  const tasks = useOwnerTasks(); const create = useCreateOwnerTask(); const setStatus = useSetOwnerTaskStatus();
  const [title,setTitle]=useState(""); const [notes,setNotes]=useState(""); const [dueAt,setDueAt]=useState(""); const [priority,setPriority]=useState<"low"|"normal"|"high">("normal"); const [showDone,setShowDone]=useState(false);
  const visible=useMemo(()=>(tasks.data??[]).filter((t)=>showDone?t.status!=="open":t.status==="open"),[tasks.data,showDone]);
  const submit=async(e:FormEvent)=>{e.preventDefault(); if(title.trim().length<3)return; try{await create.mutateAsync({title,notes,dueAt:dueAt?new Date(dueAt).toISOString():undefined,priority});setTitle("");setNotes("");setDueAt("");setPriority("normal");toast.success("Task added");}catch(error){toast.error((error as Error).message||"Could not add task");}};
  const change=async(id:string,status:"open"|"completed")=>{try{await setStatus.mutateAsync({id,status});toast.success(status==="completed"?"Task completed":"Task reopened");}catch(error){toast.error((error as Error).message||"Could not update task");}};
  return <div className="max-w-5xl space-y-6"><div><h1 className="text-2xl font-bold text-brand-navy">Tasks</h1><p className="mt-1 text-sm text-muted-foreground">One owner queue for follow-ups across the CRM.</p></div>
    <form onSubmit={(e)=>void submit(e)} className="grid gap-3 rounded-xl border border-border bg-white p-5 shadow-sm md:grid-cols-2"><input aria-label="Task title" required minLength={3} value={title} onChange={(e)=>setTitle(e.target.value)} placeholder="What needs to happen?" className="rounded-lg border border-border px-3 py-2 text-sm md:col-span-2"/><textarea aria-label="Task notes" value={notes} onChange={(e)=>setNotes(e.target.value)} placeholder="Notes (optional)" className="rounded-lg border border-border px-3 py-2 text-sm md:col-span-2"/><input aria-label="Due date" type="datetime-local" value={dueAt} onChange={(e)=>setDueAt(e.target.value)} className="rounded-lg border border-border px-3 py-2 text-sm"/><select aria-label="Priority" value={priority} onChange={(e)=>setPriority(e.target.value as typeof priority)} className="rounded-lg border border-border px-3 py-2 text-sm"><option value="low">Low priority</option><option value="normal">Normal priority</option><option value="high">High priority</option></select><button disabled={create.isPending||title.trim().length<3} className="inline-flex items-center justify-center gap-2 rounded-lg bg-brand-teal px-4 py-2 text-sm font-semibold text-white disabled:opacity-50 md:col-span-2">{create.isPending?<Loader2 className="h-4 w-4 animate-spin"/>:<Plus className="h-4 w-4"/>}Add task</button></form>
    <div className="flex gap-2"><button onClick={()=>setShowDone(false)} className={`rounded-full px-4 py-2 text-sm ${!showDone?"bg-brand-navy text-white":"border border-border bg-white"}`}>Open</button><button onClick={()=>setShowDone(true)} className={`rounded-full px-4 py-2 text-sm ${showDone?"bg-brand-navy text-white":"border border-border bg-white"}`}>Completed</button></div>
    {tasks.isLoading&&<p className="text-sm text-muted-foreground">Loading tasks...</p>}{tasks.isError&&<p className="rounded-lg bg-red-50 p-4 text-sm text-red-700">Could not load tasks.</p>}
    <div className="space-y-3">{visible.map((task)=>{const overdue=task.status==="open"&&task.due_at&&new Date(task.due_at)<new Date();return <article key={task.id} className={`flex flex-wrap items-center justify-between gap-4 rounded-xl border bg-white p-4 shadow-sm ${overdue?"border-red-200":"border-border"}`}><div><div className="flex items-center gap-2"><h2 className="font-semibold text-brand-navy">{task.title}</h2><span className={`rounded-full px-2 py-0.5 text-xs ${task.priority==="high"?"bg-red-100 text-red-700":"bg-slate-100 text-slate-600"}`}>{task.priority}</span></div>{task.notes&&<p className="mt-1 text-sm text-muted-foreground">{task.notes}</p>}<p className={`mt-1 text-xs ${overdue?"font-semibold text-red-600":"text-muted-foreground"}`}>{task.due_at?`${overdue?"Overdue · ":"Due · "}${new Date(task.due_at).toLocaleString("en-ZA")}`:"No due date"}</p></div><button disabled={setStatus.isPending} onClick={()=>void change(task.id,task.status==="open"?"completed":"open")} className="inline-flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-sm font-medium text-brand-navy disabled:opacity-50">{task.status==="open"?<Check className="h-4 w-4"/>:<RotateCcw className="h-4 w-4"/>}{task.status==="open"?"Complete":"Reopen"}</button></article>;})}{!tasks.isLoading&&visible.length===0&&<p className="rounded-xl border border-border bg-white p-8 text-center text-sm text-muted-foreground">No tasks in this view.</p>}</div>
  </div>;
}
